#ifndef HPACK_TABLE_H
#define HPACK_TABLE_H

#include <stddef.h>
#include "http_message.h"

static const HttpHeaderField static_table[] = {
    {":authority",                 "",                10, 0},
    {":method",                    "GET",             7,  3},
    {":method",                    "POST",            7,  4},
    {":path",                      "/",               5,  1},
    {":path",                      "/index.html",     5,  11},
    {":scheme",                    "http",            7,  4},
    {":scheme",                    "https",           7,  5},
    {":status",                    "200",             7,  3},
    {":status",                    "204",             7,  3},
    {":status",                    "206",             7,  3},
    {":status",                    "304",             7,  3},
    {":status",                    "400",             7,  3},
    {":status",                    "404",             7,  3},
    {":status",                    "500",             7,  3},
    {"accept-charset",             "",                15, 0},
    {"accept-encoding",            "gzip, deflate",   15, 13},
    {"accept-language",            "",                15, 0},
    {"accept-ranges",              "",                13, 0},
    {"accept",                     "",                6,  0},
    {"access-control-allow-origin","",                27, 0},
    {"age",                        "",                3,  0},
    {"allow",                      "",                5,  0},
    {"authorization",              "",                13, 0},
    {"cache-control",              "",                13, 0},
    {"content-disposition",        "",                19, 0},
    {"content-encoding",           "",                16, 0},
    {"content-language",           "",                16, 0},
    {"content-length",             "",                14, 0},
    {"content-location",           "",                16, 0},
    {"content-range",              "",                13, 0},
    {"content-type",               "",                12, 0},
    {"cookie",                     "",                6,  0},
    {"date",                       "",                4,  0},
    {"etag",                       "",                4,  0},
    {"expect",                     "",                6,  0},
    {"expires",                    "",                7,  0},
    {"from",                       "",                4,  0},
    {"host",                       "",                4,  0},
    {"if-match",                   "",                8,  0},
    {"if-modified-since",          "",                17, 0},
    {"if-none-match",              "",                13, 0},
    {"if-range",                   "",                8,  0},
    {"if-unmodified-since",        "",                19, 0},
    {"last-modified",              "",                13, 0},
    {"link",                       "",                4,  0},
    {"location",                   "",                8,  0},
    {"max-forwards",               "",                12, 0},
    {"proxy-authenticate",         "",                18, 0},
    {"proxy-authorization",        "",                19, 0},
    {"range",                      "",                5,  0},
    {"referer",                    "",                7,  0},
    {"refresh",                    "",                7,  0},
    {"retry-after",                "",                11, 0},
    {"server",                     "",                6,  0},
    {"set-cookie",                 "",                10, 0},
    {"strict-transport-security",  "",                25, 0},
    {"transfer-encoding",          "",                17, 0},
    {"user-agent",                 "",                10, 0},
    {"vary",                       "",                4,  0},
    {"via",                        "",                3,  0},
    {"www-authenticate",           "",                16, 0}
};

#endif
