#ifndef LOG_LEVELS_H
#define LOG_LEVELS_H

#define LOG_LEVEL_TRACE 0
#define LOG_LEVEL_DEBUG 1
#define LOG_LEVEL_INFO 2
#define LOG_LEVEL_WARNING 3
#define LOG_LEVEL_ERROR 4
#define LOG_LEVEL_NONE 5

#define LOG_LEVEL LOG_LEVEL_NONE

#endif
